# Generated by Django 6.0.6 on 2026-07-04 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-start_time'], 'permissions': [('can_view_all_mailings', 'Can view all mailings'), ('can_disable_mailings', 'Can disable mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 4, 11, 45, 9, 304658, tzinfo=datetime.timezone.utc), help_text='Укажите дату и время, когда рассылка должна закончиться', verbose_name='Дата и время окончания отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 4, 11, 46, 21, 459200, tzinfo=datetime.timezone.utc), help_text='Укажите дату и время, когда рассылка должна начаться', verbose_name='Дата и время начала отправки'),
            preserve_default=False,
        ),
    ]
